- type: pointOfInterest
  id: BasePOI
  abstract: true
  minimumDistance: 4000 # Some sane defaults
  maximumDistance: 8000
  spawnGamePreset: [ NFAdventure, NFPirate ]
  spawnGroup: Optional
  addComponents:
  - type: IFF
    color: "#ffa600"
    readOnly: true
  # Prevent gravity changes
  - type: ForceAnchor
